.

diff --git a/Dockerfile.feeder b/Dockerfile.feeder
--- a/Dockerfile.feeder
+++ b/Dockerfile.feeder
@@ -5,6 +5,36 @@ RUN go mod tidy
 WORKDIR /src/pw-pipeline/cmd/pw_ingest
 RUN go build -o pw_ingest .
 
-FROM alpine
-RUN apk update && apk add gcompat
+FROM debian:bullseye-20230502-slim
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN set -x && \
+    TEMP_PACKAGES=() && \
+    KEPT_PACKAGES=() && \
+    TEMP_PACKAGES+=(git) && \
+    KEPT_PACKAGES+=(ca-certificates) && \
+    apt-get update && \
+    apt-get install -y --no-install-recommends \
+        "${KEPT_PACKAGES[@]}" \
+        "${TEMP_PACKAGES[@]}" \
+        && \
+    # install S6 Overlay
+    curl --location --output /tmp/deploy-s6-overlay.sh https://raw.githubusercontent.com/mikenye/deploy-s6-overlay/master/deploy-s6-overlay.sh && \
+    sh /tmp/deploy-s6-overlay.sh && \
+    rm -f /tmp/deploy-s6-overlay.sh && \
+    # deploy healthchecks framework
+    git clone \
+      --depth=1 \
+      https://github.com/mikenye/docker-healthchecks-framework.git \
+      /opt/healthchecks-framework \
+      && \
+    rm -rf \
+      /opt/healthchecks-framework/.git* \
+      /opt/healthchecks-framework/*.md \
+      /opt/healthchecks-framework/tests \
+      && \
+    # Clean up
+    apt-get remove -y "${TEMP_PACKAGES[@]}" && \
+    apt-get autoremove -y && \
+    rm -rf /src/* /tmp/* /var/lib/apt/lists/*
+
 COPY --from=builder /src/pw-pipeline/cmd/pw_ingest/pw_ingest /usr/local/bin/pw_ingest
