Implement s6-overlay v3, Bump base image to Bookworm for mux & feed-in, More tests (#28)
* update to bullseye

* syntax match

* remove comment

* no pip

* use os packages instead of pip

* --break-system-packages.

* s6 v3

* add xz-utils

* chmod a+x

* s6 v3 script mods

* keep binutils for scipy

* troubleshoot

* troubleshoot

* reduce verbosity

* update for s6 v3

* update to s6 v3

* add xz-utils

* chmod a+x

* S6_LOGGING=0

* new s6 v3 init method

* s6 v3

* s6 v3

* troubleshoot s6

* s6 v3

* better logging

* troubleshoot logging

* troubleshoot

* troubleshoot logs

* troubleshoot log

* troubleshoot log

* finish s6 v3

* move to s6 v3

* update run scripts

* s6 overlay v3

* add S6_OVERLAY_VERSION

* add prereq pkgs

* set build shell to bash

* troubleshoot build

* tshoot

* chmod a+x

* tshoot

* tshoot

* troubleshoot healthcheck

* typo

* no READSB_STATS_EVERY in feed-in

* add test

* remove unneeded code

* more testing

* a comment

* work on TLS testing

* attempt ed25519

* work on SSL testing

* work on ssl testing

* finish TestReadFromClient

* add tests

* re-order test

* fix test

* more testing

* attempt to fix nil pointer dereference

* attemp fix sync issues

* attempt fix error

* tshoot

* tshoot

* tshoot

* tshoot

* add test TestProxyServerToClient

diff --git a/Dockerfile.bordercontrol b/Dockerfile.bordercontrol
--- a/Dockerfile.bordercontrol
+++ b/Dockerfile.bordercontrol
@@ -1,10 +1,49 @@
 FROM golang:1.21.4-bookworm AS builder
+
 COPY / /src/pw-bordercontrol
+
 WORKDIR /src/pw-bordercontrol/pw-bordercontrol
+
 RUN go mod tidy && \
     go build ./... && \
     go install ./...
 
 FROM debian:bookworm-20231030-slim
+
+ARG S6_OVERLAY_VERSION=3.1.6.0
+
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+RUN set -x && \
+    # Install required packages
+    TEMP_PACKAGES=() && \
+    KEPT_PACKAGES=() && \
+    KEPT_PACKAGES+=(net-tools) && \
+    KEPT_PACKAGES+=(procps) && \
+    KEPT_PACKAGES+=(xz-utils) && \
+    apt-get clean && \
+    apt-get update && \
+    apt-get install -y --no-install-recommends \
+        "${KEPT_PACKAGES[@]}" \
+        "${TEMP_PACKAGES[@]}" \
+        && \
+    # Clean up
+    apt-get remove -y "${TEMP_PACKAGES[@]}" && \
+    apt-get autoremove -y && \
+    rm -rf /src/* /tmp/* /var/lib/apt/lists/*
+
 COPY --from=builder /go/bin/bordercontrol /usr/local/bin/bordercontrol
-ENTRYPOINT [ "/usr/local/bin/bordercontrol" ]
+COPY pw-bordercontrol/rootfs/ /
+
+# Deploy s6 overlay
+ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
+RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
+ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
+RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
+
+# Configure s6 overlay
+ENV S6_LOGGING=0 \
+    S6_VERBOSITY=1
+
+# Set s6 init as entrypoint
+ENTRYPOINT [ "/init" ]
